### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ItsAleph** [leothewolf/softdump#1]
Of course the README already states that

> You are free to use any of the codes listed on here for any type of project.

but adding license will ensure the "Open-Source"-ity of your code. If you need an advice what license to choose, there's an amazing website by the GitHub authors: https://choosealicense.com/

**Comment by leothewolf** [comment]
> Of course the README already states that
> 
> > You are free to use any of the codes listed on here for any type of project.
> 
> but adding license will ensure the "Open-Source"-ity of your code. If you need an advice what license to choose, there's an amazing website by the GitHub authors: https://choosealicense.com/

Noted thanks a lot for that Ill add the license

**Comment by leothewolf** [comment]
I have added the license! Thanks a lot for pointing it out!
